import '@/app/_styles/index.css';

import { GoogleAnalytics } from '@next/third-parties/google';
import type { Metadata } from 'next';

import { pretendard } from '@/shared/config';

import { AuthSession, MSWComponent, QueryProvider } from './_providers';

const gaId = process.env.GA_ID ?? '';

export const metadata: Metadata = {
  title: 'NextPwa',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
  icons: { apple: '/icon.png' },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='ko'>
      <body className={pretendard.className}>
        <QueryProvider>
          <MSWComponent />
          <AuthSession>{children}</AuthSession>
        </QueryProvider>
      </body>
      <GoogleAnalytics gaId={gaId} />
    </html>
  );
}
