import { GoogleAnalytics } from '@next/third-parties/google';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import {
  AuthSession,
  MSWComponent,
  QueryProvider,
  StyledComponentsRegistry,
} from './_providers';
import { GlobalStyle } from './_styles';

const inter = Inter({ subsets: ['latin'] });

const gaId = process.env.GA_ID ?? '';

export const metadata: Metadata = {
  title: 'NextPwa',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
  icons: { apple: '/icon.png' },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='ko'>
      <body className={inter.className}>
        <QueryProvider>
          <StyledComponentsRegistry>
            <GlobalStyle />
            <MSWComponent />
            <AuthSession>{children}</AuthSession>
          </StyledComponentsRegistry>
        </QueryProvider>
      </body>
      <GoogleAnalytics gaId={gaId} />
    </html>
  );
}
