name: 'jest test'
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - '**'
jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: npm install
        run: npm install
      - name: run text
        run: npm run test
